#!/usr/bin/env python3
"""
Image to Binary Converter for REMU NPU Testing

Converts images to binary format for embedding in REMU tests.
Supports both float32 (for reference) and int8 (for NPU) formats.

Usage:
    # Convert single image
    python image_to_bin.py --image cat.jpg --output cat.bin --format int8
    
    # Convert multiple images to combined binary
    python image_to_bin.py --image_dir ./test_images/ --output images.bin --format int8
    
    # Generate assembly include file (like slider example)
    python image_to_bin.py --image cat.jpg --output images/ --generate_asm

Output formats:
    - int8:    Quantized INT8 for NPU (NCHW layout)
    - float32: Full precision float32 (NCHW layout)
    - raw:     Raw pixel bytes RGB (HWC layout, no preprocessing)
"""

import os
import sys
import argparse
import struct
import numpy as np
from PIL import Image


def preprocess_for_npu(image_path, height=224, width=224, 
                       mean=(123.68, 116.78, 103.94),
                       scale=1.0/128.0):
    """
    Preprocess image for NPU inference with INT8 quantization.
    
    Args:
        image_path: Path to input image
        height: Target height (default 224 for ImageNet)
        width: Target width (default 224 for ImageNet)
        mean: ImageNet mean values (RGB)
        scale: Quantization scale (maps [-128, 127] to float range)
        
    Returns:
        (int8_data, float_data): Quantized and original preprocessed data
    """
    # Load and resize image
    img = Image.open(image_path).convert('RGB')
    img = img.resize((width, height), Image.BILINEAR)
    
    # Convert to numpy (HWC format)
    img_data = np.array(img, dtype=np.float32)
    
    # Apply ImageNet normalization
    mean_arr = np.array(mean, dtype=np.float32)
    img_normalized = img_data - mean_arr
    
    # Convert to NCHW format
    img_nchw = img_normalized.transpose(2, 0, 1)  # HWC -> CHW
    img_nchw = np.expand_dims(img_nchw, axis=0)   # CHW -> NCHW
    
    # Quantize to INT8
    # Typical range after normalization: roughly [-128, 128]
    # We map this to [-128, 127] for int8
    img_quantized = np.clip(np.round(img_nchw * scale), -128, 127).astype(np.int8)
    
    return img_quantized, img_nchw


def preprocess_raw(image_path, height=224, width=224):
    """
    Get raw pixel data without normalization.
    
    Returns RGB pixels in HWC format as uint8.
    """
    img = Image.open(image_path).convert('RGB')
    img = img.resize((width, height), Image.BILINEAR)
    return np.array(img, dtype=np.uint8)


def save_binary(data, output_path, dtype='int8'):
    """Save numpy array as binary file."""
    if dtype == 'int8':
        data = data.astype(np.int8)
    elif dtype == 'float32':
        data = data.astype(np.float32)
    elif dtype == 'uint8':
        data = data.astype(np.uint8)
    
    data.tofile(output_path)
    return data.nbytes


def generate_header(images_info, output_path, array_name="test_images"):
    """Generate C header file with image metadata."""
    lines = [
        "/**",
        " * Test Images Header",
        " * Generated by image_to_bin.py",
        " */",
        "",
        f"#ifndef __TEST_IMAGES_H__",
        f"#define __TEST_IMAGES_H__",
        "",
        "#include <stdint.h>",
        "",
        f"#define NUM_TEST_IMAGES {len(images_info)}",
        "",
        "typedef struct {",
        "    const char* name;",
        "    int width;",
        "    int height;",
        "    int channels;",
        "    int offset;",
        "    int size;",
        "    int expected_class;  // -1 if unknown",
        "} TestImageInfo;",
        "",
        f"static const TestImageInfo {array_name}[NUM_TEST_IMAGES] = {{",
    ]
    
    for info in images_info:
        lines.append(f'    {{ "{info["name"]}", {info["width"]}, {info["height"]}, '
                    f'{info["channels"]}, {info["offset"]}, {info["size"]}, '
                    f'{info["expected_class"]} }},')
    
    lines.extend([
        "};",
        "",
        "// Declare external image data (defined in .S file)",
        "extern const int8_t test_image_data[];",
        "extern const int8_t test_image_data_end[];",
        "",
        f"#endif // __TEST_IMAGES_H__",
    ])
    
    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))


def generate_assembly(images_info, bin_files, output_dir, data_name="test_image_data"):
    """Generate assembly file for including binary images (like slider example)."""
    asm_path = os.path.join(output_dir, "images.S")
    
    lines = [
        "/**",
        " * Test Image Data Assembly",
        " * Generated by image_to_bin.py",
        " *",
        " * Include binary image files for REMU NPU testing",
        " */",
        "",
        ".section .rodata",
        f".global {data_name}, {data_name}_end",
        ".p2align 3",
        f"{data_name}:",
    ]
    
    for bin_file in bin_files:
        rel_path = os.path.basename(bin_file)
        lines.append(f'.incbin "{rel_path}"')
    
    lines.append(f"{data_name}_end:")
    lines.append("")
    
    with open(asm_path, 'w') as f:
        f.write('\n'.join(lines))
    
    return asm_path


def process_image(image_path, output_dir, format_type='int8', 
                  width=224, height=224, verbose=True):
    """Process single image and save binary."""
    basename = os.path.splitext(os.path.basename(image_path))[0]
    
    if format_type == 'int8':
        int8_data, float_data = preprocess_for_npu(image_path, height, width)
        bin_path = os.path.join(output_dir, f"{basename}.bin")
        size = save_binary(int8_data, bin_path, 'int8')
        data_shape = int8_data.shape
    elif format_type == 'float32':
        _, float_data = preprocess_for_npu(image_path, height, width)
        bin_path = os.path.join(output_dir, f"{basename}.bin")
        size = save_binary(float_data, bin_path, 'float32')
        data_shape = float_data.shape
    elif format_type == 'raw':
        raw_data = preprocess_raw(image_path, height, width)
        bin_path = os.path.join(output_dir, f"{basename}.bin")
        size = save_binary(raw_data, bin_path, 'uint8')
        data_shape = raw_data.shape
    else:
        raise ValueError(f"Unknown format: {format_type}")
    
    if verbose:
        print(f"  {basename}: {data_shape} -> {size} bytes")
    
    return {
        "name": basename,
        "path": bin_path,
        "width": width,
        "height": height,
        "channels": 3,
        "offset": 0,  # Will be updated when combining
        "size": size,
        "expected_class": -1,  # Unknown
        "format": format_type,
    }


def combine_binaries(bin_files, output_path):
    """Combine multiple binary files into one."""
    offsets = []
    current_offset = 0
    
    with open(output_path, 'wb') as outf:
        for bin_file in bin_files:
            offsets.append(current_offset)
            with open(bin_file, 'rb') as inf:
                data = inf.read()
                outf.write(data)
                current_offset += len(data)
                # Align to 4 bytes
                padding = (4 - (len(data) % 4)) % 4
                outf.write(b'\x00' * padding)
                current_offset += padding
    
    return offsets, current_offset


def main():
    parser = argparse.ArgumentParser(description="Convert images to binary for REMU testing")
    parser.add_argument("--image", help="Single image file")
    parser.add_argument("--image_dir", help="Directory of images")
    parser.add_argument("--output", required=True, help="Output file or directory")
    parser.add_argument("--format", choices=['int8', 'float32', 'raw'], default='int8',
                       help="Output format (default: int8)")
    parser.add_argument("--width", type=int, default=224, help="Target width")
    parser.add_argument("--height", type=int, default=224, help="Target height")
    parser.add_argument("--generate_asm", action="store_true", 
                       help="Generate assembly include file")
    parser.add_argument("--generate_header", action="store_true",
                       help="Generate C header file")
    parser.add_argument("--combine", action="store_true",
                       help="Combine all images into single binary")
    args = parser.parse_args()
    
    # Create output directory if needed
    if args.generate_asm or args.image_dir:
        os.makedirs(args.output, exist_ok=True)
        output_dir = args.output
    else:
        output_dir = os.path.dirname(args.output) or "."
        os.makedirs(output_dir, exist_ok=True)
    
    images_info = []
    bin_files = []
    
    if args.image:
        # Single image
        info = process_image(args.image, output_dir, args.format, 
                           args.width, args.height)
        images_info.append(info)
        bin_files.append(info["path"])
        
    elif args.image_dir:
        # Multiple images
        image_extensions = ('.jpg', '.jpeg', '.png', '.bmp', '.gif')
        image_files = sorted([f for f in os.listdir(args.image_dir) 
                             if f.lower().endswith(image_extensions)])
        
        if not image_files:
            print(f"No images found in {args.image_dir}")
            return
        
        print(f"Processing {len(image_files)} images...")
        
        for img_file in image_files:
            img_path = os.path.join(args.image_dir, img_file)
            info = process_image(img_path, output_dir, args.format,
                               args.width, args.height)
            images_info.append(info)
            bin_files.append(info["path"])
    else:
        print("Please specify --image or --image_dir")
        return
    
    # Combine if requested
    if args.combine and len(bin_files) > 1:
        combined_path = os.path.join(output_dir, "images_combined.bin")
        offsets, total_size = combine_binaries(bin_files, combined_path)
        
        # Update offsets
        for i, info in enumerate(images_info):
            info["offset"] = offsets[i]
        
        print(f"\nCombined: {combined_path} ({total_size} bytes)")
    
    # Generate header if requested
    if args.generate_header:
        header_path = os.path.join(output_dir, "test_images.h")
        generate_header(images_info, header_path)
        print(f"Header: {header_path}")
    
    # Generate assembly if requested
    if args.generate_asm:
        asm_path = generate_assembly(images_info, bin_files, output_dir)
        print(f"Assembly: {asm_path}")
    
    # Print summary
    print(f"\nSummary:")
    print(f"  Images: {len(images_info)}")
    print(f"  Format: {args.format}")
    print(f"  Size: {args.width}x{args.height}")
    total_bytes = sum(info["size"] for info in images_info)
    print(f"  Total: {total_bytes} bytes ({total_bytes/1024:.1f} KB)")


if __name__ == "__main__":
    main()
