#!/usr/bin/env python3
"""
REMU Configuration Generator
Reads .config and generates src/generated/config.rs with proper constants
"""

import re
import sys
import os
from pathlib import Path

def parse_config(config_file):
    """Parse .config file and return dictionary of config values"""
    configs = {}
    
    if not os.path.exists(config_file):
        print(f"Warning: {config_file} not found")
        return configs

    with open(config_file, 'r') as f:
        for line in f:
            line = line.strip()
            
            # Skip comments and empty lines
            if not line or line.startswith('#'):
                continue
            
            # Match CONFIG_XXX=value or CONFIG_XXX=y
            if '=' in line:
                key, value = line.split('=', 1)
                
                # Strip CONFIG_ prefix if present
                if key.startswith('CONFIG_'):
                    key = key[7:]
                
                # Remove quotes from string values for processing
                value = value.strip()
                configs[key] = value
    
    return configs

def generate_rust_code(configs):
    """Generate Rust code from parsed config"""
    
    lines = []
    lines.append("// Auto-generated from .config - DO NOT EDIT MANUALLY")
    lines.append("// Generated by scripts/gen_config.py")
    lines.append("")
    lines.append("#![allow(dead_code)]")
    lines.append("")
    
    # Generate constants
    for key, value in sorted(configs.items()):
        # Determine value and type
        # Remove quotes for analysis
        clean_value = value.strip('"')
        
        # Upper case key for Rust constant convention
        const_key = key.upper()
        
        if clean_value == 'y':
            rust_type = 'bool'
            rust_val = 'true'
        elif clean_value == 'n':
            rust_type = 'bool'
            rust_val = 'false'
        elif value.startswith('0x') or value.startswith('0X'):
            # Hex number
            # Special case for addresses/sizes that might be u64
            if const_key in ['TRACE_START', 'TRACE_END', 'FTRACE_BUF']:
                rust_type = 'u64'
            else:
                rust_type = 'u32'
            rust_val = value
        elif clean_value.isdigit():
            # Decimal number
            if const_key in ['TRACE_START', 'TRACE_END', 'FTRACE_BUF']:
                rust_type = 'u64'
            else:
                rust_type = 'u32'
            rust_val = value
        else:
            # String
            rust_type = '&str'
            if not value.startswith('"'):
                rust_val = f'"{value}"'
            else:
                rust_val = value
        
        # Generate constant
        lines.append(f'pub const {const_key}: {rust_type} = {rust_val};')
    
    return '\n'.join(lines) + '\n'

def main():
    # Paths
    # Assuming script is in scripts/ and run from project root or scripts/
    script_dir = Path(__file__).parent.resolve()
    remu_home = script_dir.parent
    
    config_file = remu_home / '.config'
    # Ensure src/generated exists
    output_dir = remu_home / 'src' / 'generated'
    output_dir.mkdir(parents=True, exist_ok=True)
    
    output_file = output_dir / 'config.rs'
    
    print(f"Reading config from: {config_file}")
    
    # Parse config
    configs = parse_config(config_file)
    
    # Generate Rust code
    rust_code = generate_rust_code(configs)
    
    # Write output
    with open(output_file, 'w') as f:
        f.write(rust_code)
    
    print(f"Generated {output_file}")
    print(f"  {len(configs)} configuration options")

if __name__ == '__main__':
    main()
